# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
#    command.project.create:
#        class: AppBundle\SimpleBus\Project\Handler\CreateProjectCommandHandler
#        tags: [{ name: command_handler, handles: AppBundle\SimpleBus\Projects\CreateProjectCommand }]
#        arguments: [ "@validator", "@doctrine" ]

    todo.factory:
        class: Todolist\Domain\Factory\TodoFactory
        autowire: true

    command.todo.add:
        class: Todolist\Application\Command\AddTodoCommand

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Todolist\UI\Http\Controller\:
        resource: '../src/Todolist/UI/Http/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
